require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
vim.cmd "colorscheme gruvbox"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.vim-header"
require "user.vimtex"
require "user.neorg"
require "user.lualine"
